org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.21
enabled_platforms=fabric,neoforge

mod_id=shrink
mod_author=gigabit101

archives_base_name=shrink
mod_version=2.0.1
maven_group=net.gigabit101
curseforge_id=426386
artifact_type=release

architectury_version=13.0.6
parchment_minecraft_version=1.21
parchment_version=2024.11.10
polylib_version=2100.0.3-build.160

fabric_loader_version=0.16.9
fabric_api_version=0.100.8+1.21

forge_version=51.0.0
neoforge_version=21.0.148

gekolib_version=4.5.6



