org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.21.7
enabled_platforms=fabric,neoforge

mod_id=shrink
mod_author=gigabit101

archives_base_name=shrink
mod_version=2.0.1
maven_group=net.gigabit101
curseforge_id=426386
modrinth_id=jzaTHh0C
artifact_type=release

architectury_version=17.0.8
parchment_minecraft_version=1.21.7
parchment_version=2025.07.18
polylib_version=2107.1.0.181

fabric_loader_version=0.17.2
fabric_api_version=0.129.0+1.21.7

neoforge_version=21.7.8-beta

gekolib_version=4.5.6



