plugins {
    id "com.github.johnrengelman.shadow" version "7.0.0"
    id "maven-publish"
}

loom {
    accessWidenerPath = file("src/main/resources/shrink.accesswidener")
}

configurations {
    shadowCommon
}

dependencies {
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    modCompileOnlyApi "net.creeperhost:polylib-fabric:${polylib_version}"

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
}

architectury {
    common("fabric", "neoforge")
}

sourceSets {
    main {
        resources {
            srcDir "src/generated/resources"
        }
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }

    repositories {

    }
}
