modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/gigabit101/Shrink/issues"
license = "LGPL-3.0"

[[mods]]
modId = "shrink"
version = "${version}"
displayName = "Shrink"
authors = "Gigabit101"
description = '''
Honey I shrunk the children
'''
#logoFile = ""

[[dependencies.shrink]]
modId = "neoforge"
type="required" #mandatory
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrink]]
modId = "minecraft"
type="required" #mandatory
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrink]]
modId = "architectury"
type="required" #mandatory
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.shrink]]
modId = "polylib"
type="required" #mandatory
versionRange = "[2105.0.4.174,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shrink.mixins.json"
